### ISSUE TITLE
Recommended hyperparams for high-resolution input

### ISSUE THREAD

**Issue by Masaaki-75** [csguoh/MambaIR#12]
Hi! Thanks for open-sourcing such good work!

I am trying to apply MambaIR to my artifact removal task. Due to the artifacts being globally distributed, I didn't crop the image to a smaller size, trying to maintain the global information about the artifacts. And I failed to launch training, running out of the GPU memory.

The original image size is 512. I am wondering if MambaIR can be applied with such full-resolution images directly? If so, would you be so kind to share knowledge on the hyperparams you recommend (`patch_size`, `embed_dim`, etc)? 

Or,  when inferring on a high-resolution image, is it a convention to first crop the input image to a smaller size like 64x64, and do multiple inference patch-by-patch?

Thanks :)

**Comment by csguoh** [comment]
In super-resolution or other restoration tasks, we also need to deal with some lage-size images. The common practice is to crop the img in to small patches during training, so as to allow a low-gpu cost, and then use the full-scale img as input during inference.
