### ISSUE TITLE
About inference speed

### ISSUE THREAD

**Issue by qiuzidian** [csguoh/MambaIR#13]
Could you please provide an actual inference speed comparison?

**Comment by csguoh** [comment]
We have added the FLOPs and #param comparison in Tab.4 in the new Arxiv version.

**Comment by qiuzidian** [comment]
I'm sorry, but I have one more question. When I was testing visionmamba before, I found that with the same floats, the inference delay of visionmamba is about 5 times that of CNN. This seems to be a disadvantage of using mamba for vision?

**Comment by csguoh** [comment]
Thanks for rising this concern. The hardware accelaration of Mamba is at early stage. Since the parallel scan algorithms ensure that parallel computation is possible, we believe future efforts can well address this concern.
