### ISSUE TITLE
About training speed

### ISSUE THREAD

**Issue by zhaomengjiao123** [csguoh/MambaIR#14]
Hello, your work is excellent! When I use MambaIR in my own work, I find that its training speed is very slow. When the number of iterations is 129500, it is expected to take 6 days, which is much longer than the time spent in transformer application. Is this normal? What is your opinion? I have tried to reduce the number of channels embedded with features and the number of RSSB blocks in them, my image size is 128, looking forward to your reply!

**Comment by csguoh** [comment]
Hi,
In our implementation, it took us about 5-6 days to complete the 500K iteration using 8 V100 GPUs. Maybe you can run the MambaIR-light model as a trial to see the results, also the patch size of 128 is a bit big (considering the quadratic increase in the number of tokens), we used patch size 64 in original setting which also works well.

**Comment by zhaomengjiao123** [comment]
您发给我的信件我已经收到。
