### ISSUE TITLE
Inquiry Regarding Training Requirements for light-sr Model

### ISSUE THREAD

**Issue by hezhiyang2000** [csguoh/MambaIR#16]
Hello,

I've noticed that the author has mentioned across various platforms that training the MambaIR model generally requires about 8 NVIDIA V100 GPUs for a duration of approximately 7 days. I am curious to know if this specification also applies to the training of the **light-sr model**. Could you please provide some insights on whether the same hardware and timeframe are recommended for light-sr, or if there are different requirements for optimal training results?

Thank you for your time and assistance.

Best regards.

**Comment by csguoh** [comment]
Hi, 
The light-sr model can be trained with NVIDIA 3090 GPUs and it requires less training time than classic SR. You can refer the log file released in the README.md for more device info ;D
