### ISSUE TITLE
A Humble Request for Assistance

### ISSUE THREAD

**Issue by xaswq** [csguoh/MambaIR#18]
Dear esteemed author,

First and foremost, I would like to express my heartfelt gratitude for your remarkable work. After nearly 5 days of diligent training, the model has successfully completed its learning process. For testing purposes, I selected the final model, `MambaIR-main/experiments/MambaIR_SR_x2/models/net_g_latest.pth`. If it wouldn't be too much trouble, could you kindly take a moment to review my approach and confirm whether it is correct? 

The command I employed for testing is as follows:

```
python basicsr/test.py -opt options/test/test_MambaIR_SR_x2.yml
```

I am incredibly appreciative of your thoughtful reminder. As per your guidance, I have made sure to include the path in the test script to avoid any potential errors.

![image](https://github.com/csguoh/MambaIR/assets/85377380/840d66bc-bfa2-4112-a4ea-c1dec2a9d1e1)

```

2024-04-11 20:25:22,989 INFO: Dataset [PairedImageDataset] - Set5 is built.
2024-04-11 20:25:22,990 INFO: Number of test images in Set5: 5
2024-04-11 20:25:23,033 INFO: Dataset [PairedImageDataset] - Set14 is built.
2024-04-11 20:25:23,034 INFO: Number of test images in Set14: 14
2024-04-11 20:25:23,111 INFO: Dataset [PairedImageDataset] - B100 is built.
2024-04-11 20:25:23,112 INFO: Number of test images in B100: 100
2024-04-11 20:25:23,187 INFO: Dataset [PairedImageDataset] - Urban100 is built.
2024-04-11 20:25:23,187 INFO: Number of test images in Urban100: 100
2024-04-11 20:25:23,243 INFO: Dataset [PairedImageDataset] - Manga109 is built.
2024-04-11 20:25:23,244 INFO: Number of test images in Manga109: 109
2024-04-11 20:25:23,802 INFO: Network [MambaIR] is created.
2024-04-11 20:25:27,104 INFO: Loading MambaIR model from /aiarena/gpfs/MambaIR-main/experiments/MambaIR_SR_x2/models/net_g_latest.pth, with param key: [params].
2024-04-11 20:25:27,368 INFO: Model [MambaIRModel] is created.
2024-04-11 20:25:27,368 INFO: Testing Set5...
2024-04-11 20:25:33,674 INFO: Validation Set5
         # psnr: 38.3964        Best: 38.3964 @ test_MambaIR_SR_x2 iter
         # ssim: 0.9619 Best: 0.9619 @ test_MambaIR_SR_x2 iter

2024-04-11 20:25:33,674 INFO: Testing Set14...
2024-04-11 20:25:58,600 INFO: Validation Set14
         # psnr: 34.4674        Best: 34.4674 @ test_MambaIR_SR_x2 iter
         # ssim: 0.9245 Best: 0.9245 @ test_MambaIR_SR_x2 iter

2024-04-11 20:25:58,601 INFO: Testing B100...
2024-04-11 20:27:38,379 INFO: Validation B100
         # psnr: 32.4877        Best: 32.4877 @ test_MambaIR_SR_x2 iter
         # ssim: 0.9036 Best: 0.9036 @ test_MambaIR_SR_x2 iter

2024-04-11 20:27:38,379 INFO: Testing Urban100...
2024-04-11 20:37:53,034 INFO: Validation Urban100
         # psnr: 33.7748        Best: 33.7748 @ test_MambaIR_SR_x2 iter
         # ssim: 0.9415 Best: 0.9415 @ test_MambaIR_SR_x2 iter

2024-04-11 20:37:53,036 INFO: Testing Manga109...
2024-04-11 20:50:51,653 INFO: Validation Manga109
         # psnr: 39.7395        Best: 39.7395 @ test_MambaIR_SR_x2 iter
         # ssim: 0.9794 Best: 0.9794 @ test_MambaIR_SR_x2 iter

```
Is this all right?

Your expertise and assistance in this matter would be immensely valued.

With utmost respect and gratitude,
xaswq

**Comment by csguoh** [comment]
Hi, thanks for your interesting in our work.
From the above testing results, it seems the model you trained can be further improved to achieve our reported performance. Have you tested with our released model? And what the specific training config you have used to train your model?

**Comment by xaswq** [comment]
Dear Author,

I trained a model based on your open-source code on four NVIDIA 3090 GPUs for approximately five days. The training command used was as follows: 

```
python -m torch.distributed.launch --nproc_per_node=4 --master_port=1234 basicsr/train.py -opt options/train/train_MambaIR_SR_x2.yml --launcher pytorch 
```

The configuration for the training was set up as detailed in your documentation, focusing on image super-resolution with the MambaIR model at a scale of 2, using the DF2K and Set14 datasets for training and validation respectively. The objective was to replicate your results and understand the method's applicability in other domains.

```
# general settings for image SR training
name: MambaIR_SR_x2
model_type: MambaIRModel
scale: 2
num_gpu: 4
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    task: SR
    name: DF2K
    type: PairedImageDataset
    dataroot_gt:
      - /xxx/codes/MambaIR-main/datasets/DF2K/DF2K_train_HR
    dataroot_lq:
      - /xxx/codes/MambaIR-main/datasets/DF2K/DF2K_train_LR_bicubic/X2
    filename_tmpl: '{}x2'
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 32
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: xxxx/codes/MambaIR-main/datasets/SR/Set14/HR
    dataroot_lq: xxx/codes/MambaIR-main/datasets/SR/Set14/LR_bicubic/X2
    filename_tmpl: '{}x2'
    io_backend:
      type: disk

# network structures
network_g:
  type: MambaIR
  upscale: 2
  in_chans: 3
  img_size: 64
  img_range: 1.
  d_state: 16
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    #lr: !!float 2e-4
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    #milestones: [5000, 10000, 15000, 20000，25000，30000，35000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true



# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

```
I am pleased to report that the performance of the model closely matches the expected outcomes, demonstrating the robustness and versatility of your approach. This success has greatly encouraged me to explore further applications of your methodology in different fields.

Thank you very much for your contributions to the field and for your support to the community.

Sincerely,

xaswq

**Comment by csguoh** [comment]
Thanks for your feedback

From the above training config, it seems that the total batch size is slightly different from ours. For example, we used 8 GPUs with batch size 4 per GPU, resulting total batch size 32. During training, we find a large total batch size allows a more stable gradient for SR model and can converge with less training iterations.

You can check your training log to find whether the model you trained has converged. Or you can also test our model with MambaIR-light, which is more light to allow a large batch size and fast training.

Let me know if you have any other question :）
