### ISSUE TITLE
The param of MambaIR_lightSR is more than 1M, which is not the same as Table 5 of the paper.

### ISSUE THREAD

**Issue by zp-cloud** [csguoh/MambaIR#20]
I run the file of flops_param.py revising the parameter in the function of buildMambaIR as the same as the MambaIR_lightSR. But the result is 1.138M, not the same as Table 5 of the paper. Why does this happen? （This picture is the parameter of MambaIR_lightSR I modified based on train_MambaIR_lightSR_x2.yml）
![20240414220141](https://github.com/csguoh/MambaIR/assets/66307634/f0f887ac-f613-44b0-8ed5-fab2ffd34374)

**Comment by csguoh** [comment]
Hi, 
The `MambaIR.py` in `./analysis` is for classicSR param and MACs calculation. If you want to compute those in lightSR, some difference between lightSR and classicSR should be noticed, such as the `compression_ratiao` of CAB in [this line](https://github.com/csguoh/MambaIR/blob/0eba085901e5fa317fc855d66c34099cee843fa8/analysis/model_zoo/mambaIR.py#L41). Moreover, as stated in the original Mamba issue, the param&flops calculation has some bug with existing third-part param&flops calculation library, and we are trying hard to solve this, if anyone has addressed this, you can pull a request for sharing  your code, thx :)

**Comment by zp-cloud** [comment]
> 嗨，in 用于 classicSR 参数和 MAC 计算。如果要在 lightSR 中计算这些，则应注意 lightSR 和 classicSR 之间的一些差异，例如[此行](https://github.com/csguoh/MambaIR/blob/0eba085901e5fa317fc855d66c34099cee843fa8/analysis/model_zoo/mambaIR.py#L41)中的 CAB。此外，正如原始 Mamba 问题中所述，param&flops 计算与现有的第三方 param&flops 计算库存在一些错误，我们正在努力解决这个问题，如果有人解决了这个问题，您可以拉取共享代码的请求，谢谢:)`MambaIR.py``./analysis``compression_ratiao`

Thank you for your patient answer，and my question is solved.(The compression_ratiao of CAB in lightSR is 6 not 3, and can be found in mambair_arch.py)

**Comment by zp-cloud** [comment]
> Hi, The `MambaIR.py` in `./analysis` is for classicSR param and MACs calculation. If you want to compute those in lightSR, some difference between lightSR and classicSR should be noticed, such as the `compression_ratiao` of CAB in [this line](https://github.com/csguoh/MambaIR/blob/0eba085901e5fa317fc855d66c34099cee843fa8/analysis/model_zoo/mambaIR.py#L41). Moreover, as stated in the original Mamba issue, the param&flops calculation has some bug with existing third-part param&flops calculation library, and we are trying hard to solve this, if anyone has addressed this, you can pull a request for sharing your code, thx :)

Thank you for your patient answer，and my question is solved.(The compression_ratiao of CAB in lightSR is 6 not 3, and can be found in mambair_arch.py)
