### ISSUE TITLE
About 'Test on Real Image Denoising' meet some questions

### ISSUE THREAD

**Issue by Mayingj** [csguoh/MambaIR#21]
Thank you for your contribution in this field, but when I was running ‘Test on Real Image Denoising’this part of the code there were two errors that I couldn't solve，The specific details are as follows：
python test_real_denoising_dnd.py
first,
![image](https://github.com/csguoh/MambaIR/assets/117135922/c4f2250f-bf7b-4e9b-bac9-4bbbcf985829)
I found that these parameters are not present in the model,such as heads: [1, 2, 4, 8],window_size: [8, 8, 8, 8],interval: [32, 16, 8, 4].So I deleted these three parameters
![image](https://github.com/csguoh/MambaIR/assets/117135922/6452eec8-4ed8-4215-b324-6a25e55fc285)

But I encountered the second error
![image](https://github.com/csguoh/MambaIR/assets/117135922/8bb4b055-62b3-43fa-8c62-4e0385e95fbe)

I downloaded ' Real image Denoising’, but it reported an error

![image](https://github.com/csguoh/MambaIR/assets/117135922/49ca3628-b30d-4f4e-aa78-bc876f6f8cc1)

So may I ask if there is anything wrong with me? What should I do?
Thank you

**Comment by ZzHowe** [comment]
请问你解决了吗
