### ISSUE TITLE
About “Train on Real Denoising” section

### ISSUE THREAD

**Issue by ContestantsD** [csguoh/MambaIR#24]
hello， when i run "python setup.py develop --no_cuda_extgf", i will recive "no option --no_cuda_extgf"
how can i address it?

**Comment by csguoh** [comment]
Hi, Did you check you have installed the right basicSR version which is given in README.md?

**Comment by hyunW3** [comment]
I think the option is "--no_cuda_ext", not "--no_cuda_extgf". 
The option is processed in https://github.com/csguoh/MambaIR/blob/59829b7154a9dcb03fbf3f9af120e9f7b7aa5194/realDenoising/setup.py#L124-L128
