### ISSUE TITLE
A Question about ERF

### ISSUE THREAD

**Issue by Yaziwel** [csguoh/MambaIR#26]
Hello, I'm encountering difficulty in visualizing the Effective Receptive Field (ERF) of models for my task in MRI super-resolution. The ERF of MambaIR appears to be typical and is displayed below:
![MambaIR_ERF](https://github.com/csguoh/MambaIR/assets/38243190/362857f2-9bba-4282-9aa0-ec04d136024f)

However, when visualizing the ERF of the SwinIR model, it displays an abnormal result as shown below:
![SwinIR_ERF](https://github.com/csguoh/MambaIR/assets/38243190/b3700cc7-605f-46b0-8df8-e91ffe7b0bf5)
I'm uncertain about the reason behind this discrepancy. Could the author provide any suggestions or insights?

**Comment by csguoh** [comment]
Hi, thank you for your interest in our work.
Swinir uses window attention, so a typical ERF visualization of a swinir model should be square, not cross-shaped. We use pre-trained SwinIR models for ERF visualization, do you use the pre-trained weights for visualization?

**Comment by Yaziwel** [comment]
> Hi, thank you for your interest in our work. Swinir uses window attention, so a typical ERF visualization of a swinir model should be square, not cross-shaped. We use pre-trained SwinIR models for ERF visualization, do you use the pre-trained weights for visualization?

Thank you for your response. I obtained comparable ERF results to yours using the well-versed SwinIR model.
