### ISSUE TITLE
你好，能帮我看看为什么运行test的时候会报这个错吗

### ISSUE THREAD

**Issue by jduyou** [csguoh/MambaIR#28]
你好，能帮我看看为什么运行test的时候会报这个错吗
![1](https://github.com/csguoh/MambaIR/assets/88967901/c417af8c-e90d-44d6-adfc-bfdec3bb81a2)

**Comment by wyy0v0** [comment]
我报错是这个
![c8c738e5f1b27cef0691fb32377c28d](https://github.com/csguoh/MambaIR/assets/170064089/e7cc158f-8279-49ed-b070-e081a79f3892)

**Comment by csguoh** [comment]
Hi, may be there is some wrong with your model register in basicsr, such as the MambaIR class definition or the config file.

**Comment by yang-yee** [comment]
I also encountered this problem. May I ask if you have resolved it?

**Comment by jduyou** [comment]
You can refer to the comment in the file test.py under the MambaIR-main/basicsr directory.
![Uploading 111.png…]()

**Comment by jduyou** [comment]
You can refer to the comment in the file test.py under the MambaIR-main/basicsr directory.
![111](https://github.com/csguoh/MambaIR/assets/88967901/97497248-9ab1-42a8-b3a8-8089865413d3)

**Comment by weirui0430** [comment]
你好 我已经加入了这句：sys.path.append，仍然报相同的错误，请问你是只加了这一句就不再报这个错误了吗

**Comment by yang-yee** [comment]
是加了两句。
basic_dir = ’你的MambaIR-main路径‘
sys.path.append(basic_dir)


y
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "csguoh/MambaIR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月11日(星期二) 下午5:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [csguoh/MambaIR] 你好，能帮我看看为什么运行test的时候会报这个错吗 (Issue #28)





 
你好 我已经加入了这句：sys.path.append，仍然报相同的错误，请问你是只加了这一句就不再报这个错误了吗

**Comment by weirui0430** [comment]
是的 我也加了同样的这两句，MambaIR-main路径就是这整个项目的文件夹的路径对吗

**Comment by jduyou** [comment]
可能你用包管理工具安装了basicsr，可以卸载掉试试

**Comment by weirui0430** [comment]
> 可能你用包管理工具安装了basicsr，可以卸载掉试试

已解决 谢谢
