### ISSUE TITLE
Question about visualization

### ISSUE THREAD

**Issue by tmax-cn** [csguoh/MambaIR#30]
Hi, great works, thanks for your contribution.
I would like to revising the channel activation value of the model, how to get the visualization like ↓
![Screenshot from 2024-05-21 17-04-54](https://github.com/csguoh/MambaIR/assets/59724549/024d5448-28cc-4f04-9a55-19f70bc01fe0)

Thanks
BR

**Comment by csguoh** [comment]
The right figure is obtained from the feature map [in this line](https://github.com/csguoh/MambaIR/blob/0eba085901e5fa317fc855d66c34099cee843fa8/basicsr/archs/mambair_arch.py#L376) of the original MambaIR. To obtain the left figure, you should train another variants which removes the channel attention module and visualize the same position.
