### ISSUE TITLE
测试报错

### ISSUE THREAD

**Issue by weirui0430** [csguoh/MambaIR#32]
你好，我在配好环境测试时出现了这个错误：KeyError: "No object named 'MambaIRModel' found in 'model' registry!"，请问这是为什么呢？

**Comment by 18670113** [comment]
请问你解决了吗？

**Comment by xiaoxuesheng180** [comment]
> 你好，我在配好环境测试时出现了这个错误：KeyError: "No object named 'MambaIRModel' found in 'model' registry!"，请问这是为什么呢？

请问怎么解决的？可以告知以下嘛，万分感谢。
