### ISSUE TITLE
Can the model perform image restoration tasks

### ISSUE THREAD

**Issue by Idol-Dou2021** [csguoh/MambaIR#36]
I have read the paper and have a rough idea that it can be used for super-resolution reconstruction, which means restoring low resolution to high resolution. I would like to ask if it is possible to perform image restoration tasks, such as missing a piece of the image, and if the output can complete it？

**Comment by wjkbigface** [comment]
the same question

**Comment by csguoh** [comment]
Does you mean the image inpainting?

**Comment by Idol-Dou2021** [comment]
Yes, that is to say, the image is missing one area, and then we need to complete it. I'm curious if this model can solve this task?

> 你是指图像修复吗？

**Comment by csguoh** [comment]
Theoretically, since the image inpainting tasks also belong to pixel regression, it may be possible to apply the MambaIR model for image inpainting. However, we did not include this task in our experimental setup, you may modify the code for this task.
