### ISSUE TITLE
About RealDN

### ISSUE THREAD

**Issue by Madeline-hyh** [csguoh/MambaIR#4]
Hello! It's a really good job and I'm very interested in it. But I couldn't find the real denoising network ARTUNet in the configuration file ./realDenoising/options/train_MambaIR_RealDN.yml, Could you please help to point out the specific location? Thank you.

**Comment by csguoh** [comment]
Hi, Thx for your feedback, we have fix the bug in the `train_MambaIR_RealDN.yml`. Now you can replace your original config file with this updated one to train your realDN model. Let me know if you have other question  ;D
