### ISSUE TITLE
Some problems about ckpt

### ISSUE THREAD

**Issue by liar017** [csguoh/MambaIR#48]
![image](https://github.com/user-attachments/assets/ffcd2f7f-c3df-41ad-839b-7d1b6538429b)
Hi, I ran the real-denoising test code, and encountered this error.
I have noticed in previous issues that it could be caused from the inaccurate model channel dimension or channel expand ratio of SSMs. Some attempts were made to change the params below, but the prob still existed.
![image](https://github.com/user-attachments/assets/d0933625-3c79-46da-a816-8d32179952d9)
Could you plz help me solve this issue?QAQ

**Comment by csguoh** [comment]
Hi, we have updated the realDN config files to allow the load of the pre-trained weights. You may update the code and then it will works fine.
