### ISSUE TITLE
About the Effective Receptive Field (ERF) visualization

### ISSUE THREAD

**Issue by justcyl** [csguoh/MambaIR#5]
Hi, thanks for your work! Can you show the code about the Effective Receptive Field (ERF) visualization in your paper. We are interested in this.
![image](https://github.com/csguoh/MambaIR/assets/37929641/4b7c65dd-d09b-4cc7-9c3c-d6ad509c1eb3)

**Comment by csguoh** [comment]
Hi, thx for your interest of this work. 
The relevant code is being organized, and we will make the code available as soon as possible ;D

**Comment by csguoh** [comment]
The code for ERF visualization is now available. 
I will close this issue, and you can re-open it any time you have other issues.

**Comment by yang-yee** [comment]
Sorry, I have a simple question. I would like to know how this ERF code is used? May I ask if you can inform me? Thank you！
