### ISSUE TITLE
 About the calculation of params count and MACs for lightweight Image Super-Resolution

### ISSUE THREAD

**Issue by dpnbb** [csguoh/MambaIR#6]
Thank you very much for your work! I'd like to ask, what toolkit did you use to calculate the params count and MACs? It seems that the toolkit I have here cannot compute the parameter count and MACs.

**Comment by csguoh** [comment]
Hi, thx for your interest in this work.
We use `thop` library to compute the #param and MACs, the specific python file can be found in [here](https://github.com/csguoh/MambaIR/blob/main/analysis/flops_param.py).
Let me know if you have any other question ;D

**Comment by dpnbb** [comment]
My issue has been resolved, thank you for your assistance.
