### ISSUE TITLE
Please add cuda 11.8 support with pip, instead of just working with cuda 11.7 and conda

### ISSUE THREAD

**Issue by GLOMQuyet** [csguoh/MambaIR#62]

**Comment by csguoh** [comment]
The current environment is based on CUDA11.7, however, I think it will also works well on higher CUDA version.

**Comment by GLOMQuyet** [comment]
thanks, i installed them successfully via cuda 11.8 or cuda 12.2, Error due to anaconda (i removed them and just played pip)
