### ISSUE TITLE
torch.distributed.elastic.multiprocessing.errors.ChildFailedError

### ISSUE THREAD

**Issue by formerlya** [csguoh/MambaIR#63]
![image](https://github.com/user-attachments/assets/4d05c5c6-adf7-45f5-8d1f-acab5636d4dc)
torch ：1.13.1+cu117 
 nvcc -V ： cuda_11.7.r11.7/compiler.31442593_0 
CUDA Version ：12.4
Does anyone know how to solve this situation? There should be no problem with the corresponding versions.

**Comment by formerlya** [comment]
The test part can run normally

**Comment by csguoh** [comment]
Hi, there is a bug of pytorch 1.X and 2.X, in which the name of local rank args are different. You may try `local-rank` or `local_rank` for multi-gpu training.
