### ISSUE TITLE
About the mlp_ratio in the SR x2

### ISSUE THREAD

**Issue by liboyun** [csguoh/MambaIR#7]
Thank you very much for your work! I am curious about the mlp_ratio in the SR x2 settings. 
 
In the options/train/train_MambaIR_SR_x2.yml, the mlp_ratio is 2.0, while in the log provided in [here](https://drive.google.com/file/d/1XzBkBPPb5jymKfGQO3yVePVqWxDMuaF1/view) is 4.0. 

I am wondering which one should we tend to refer? Expect for you reply.

**Comment by csguoh** [comment]
Hi, the `mlp_ratio` in the log file denotes the MLP ratio in the Transformer inherited form previous code base, which means it is a no-use hyper-parameter. In the released `yml` file, the `mlp_ratio` represent the hidden-space expansion ratio in the SSM, you can use the default value `mlp_ratio=2` to reproduce the experimental results ;D

**Comment by liboyun** [comment]
Thanks for your replies. 👯
