### ISSUE TITLE
验证结果问题

### ISSUE THREAD

**Issue by WWW-GUO** [csguoh/MambaIR#71]
您好 我在您给定的train_MambaIR_SR_x2.yml文件下，仅改变了GPU数量（3张2080ti）和在每个GPU上训练的batchsize（设为11），为什么在最终的set14数据集下的测试效果psnr为33.7864，比您论文中要低0.9左右？

**Comment by ygtreceee** [comment]
When I train MambaIR_SR_x2 on 4090 (24G), `batch_size_per_gpu` can only be set to **2**. If it is set to 4, it will cause `CUDA out of memory`. Why can you set batchsize to **11** on 2080Ti? Did you make any changes?
