### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'use_checkpoint'

### ISSUE THREAD

**Issue by tzulunyeh** [csguoh/MambaIR#75]
![螢幕擷取畫面 2024-12-07 221357](https://github.com/user-attachments/assets/9d1c36c6-7d6b-45b7-a0b5-2a18b3476e23)
TypeError: __init__() got an unexpected keyword argument 'use_checkpoint'

i use  1 gpu run 
python basicsr/train.py -opt options/train/mambairv2/train_MambaIRv2_lightSR_x2.yml

**Comment by csguoh** [comment]
Hi, 
Thanks for your report. Actually, the param `self.use_ckpt` is a redundant hyper-parameter and is not use in the model. So you can simply remove this param and it does not harm the performance.

**Comment by tzulunyeh** [comment]
I'll try it out in the coming days. Thanks for the reply!!
