### ISSUE TITLE
RealSR任务的预训练参数模型文件是否放错了？

### ISSUE THREAD

**Issue by leomessi17** [csguoh/MambaIR#9]
我是从这个链接下载的：https://drive.google.com/file/d/1ZOFzcex2g9_B6Xtf8-qnMx08OnAjKD0M/view?usp=sharing。 下载后发现checkpoint中的keys是这些：
['conv0.weight', 'conv0.bias', 'conv1.weight_orig', 'conv1.weight_u', 'conv1.weight_v', 'conv2.weight_orig', 'conv2.weight_u', 'conv2.weight_v', 'conv3.weight_orig', 'conv3.weight_u', 'conv3.weight_v', 'conv4.weight_orig', 'conv4.weight_u', 'conv4.weight_v', 'conv5.weight_orig', 'conv5.weight_u', 'conv5.weight_v', 'conv6.weight_orig', 'conv6.weight_u', 'conv6.weight_v', 'conv7.weight_orig', 'conv7.weight_u', 'conv7.weight_v', 'conv8.weight_orig', 'conv8.weight_u', 'conv8.weight_v', 'conv9.weight', 'conv9.bias'])
跟MambaIR模型没有关系，是不是放错了？我已经通过日志文件，对齐了模型结构，目前代码打印出来的模型结构和日志中的是一样的，但是加载预训练模型参数时遇到键值对不上的问题。

**Comment by csguoh** [comment]
Thanks for your kind reminder, we have updated the link of MambaIR-real.pth in the README, now you can try the real-SR model.
